# Pipeline for building debian package

stages:
  - package
  - deploy

package_bookworm:
  stage: package
  tags:
    - shell
  script:
    - mkdir build-area
    - uscan --destdir=build-area/ --download --download-current-version
    - dch --bpo ""
    - gbp buildpackage --git-overlay --git-export-dir=build-area/ --git-ignore-branch --git-ignore-new --no-sign
  artifacts:
    paths:
      - build-area/

publish:
  stage: deploy
  tags:
    - shell
  script: 
    - |
      for i in build-area/*.deb; do        j=`basename ${i}`     ;   curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}"            --upload-file ${i}            "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/igtf-policy-bundle/${CI_COMMIT_TAG}/${j}" ;     done
