# Pipeline for building debian package

stages:
  - package

package_bookworm:
  stage: package
  tags:
    - shell
  script:
    - mkdir build-area
    - uscan --destdir=build-area/ --download --download-current-version
    - dch --bpo ""
    - gbp buildpackage --git-overlay --git-export-dir=build-area/ --git-ignore-branch --git-ignore-new
