#!/bin/sh
# $1 = action ('configure' or 'reconfigure')
# $2 = current-installed-version
set -e

. /usr/share/debconf/confmodule

profile=@PROFILE@

if [ -f /etc/grid-security/igtf-policy-${profile}.conf ]; then
   . /etc/grid-security/igtf-policy-${profile}.conf
fi

if [ "$install_profile" = "yes" ]; then
    db_set igtf-profile-${profile}/install_profile yes
else
    db_set igtf-profile-${profile}/install_profile no
fi


db_input low igft-profile-${profile}/install_profile || true

db_get igft-profile-${profile}/install_profile

if [ "$RET" = yes ]; then
    # bother with possible exclusions
    # perform a substitution with available and already excluded CAs
    # transform the variable to suit the debconf multichoice format
    CA_EXCLUDED=`echo $exclude_ca | tr -s '[:space:]' ',' | sed -e 's/,*$//' -e 's/^,*//'`
    db_subst igtf-profile-${profile}/exclude_ca exclude_ca "$CA_EXCLUDED"
    db_input low igtf-profile-${profile}/exclude_ca || true
else
    # bother with possible inclusions
    CA_INCLUDED=`echo $include_ca | tr -s '[:space:]' ',' | sed -e 's/,*$//' -e 's/^,*//'`
    db_subst igtf-profile-${profile}/include_ca exclude_ca "$CA_INCLUDED"
    db_input low igtf-profile-${profile}/include_ca || true
fi
